### ISSUE TITLE
Delete Widgets disappear

### ISSUE THREAD

**Issue by rgbink** [Surye/mfp-keto-userscript#6]
[FIXME] When enabled the final table column in the Food Diary view (<td class="delete">) disappears. In order to delete a food entry, the script must be toggled off, refresh page (if auto-refresh isn't on), delete item, toggle script back on.

**Comment by rgbink** [comment]
Worked it out: use **[Stylist](https://goo.gl/ZNfzAR)** (in Chrome) or any other extension that allows automated site CSS style changes to add the following:

``` css
body#food-diary[rel~="premium"] table.table0 tbody tr td.first {
    width: 490px;
}
```
